import sys
sys.stdout.reconfigure(encoding="utf-8")
f = open("D:\\code\\llama.cpp\\paper\\LEARNING_GUIDE.md", "a", encoding="utf-8")
f.write("### 3.8 Vulkan GPU 后端中的 MoE 执行\n\n")
f.write("```\n")
f.write("tgml/src/ggml-vulkan/ 目录结构：\n")
f.write("ggml-vulkan.cpp          # 后端入口：设备管理、计算图提交\n")
f.write("vk-shader-registry.cpp   # shader 注册\n")
f.write("vk-mem.cpp               # GPU 内存管理\n")
f.write("vk-pipeline.cpp          # 计算管线\n")
f.write("*.comp 文件              # Vulkan compute shader\n")
f.write("    mul_mat.comp          # 普通矩阵乘法\n")
f.write("    mul_mat_id.comp       # mul_mat_id（MoE 专家选择）\n")
f.write("    soft_max.comp         # softmax\n")
f.write("    silu.comp             # SiLU 激活\n")
f.write("    argsort_top_k.comp    # top-k 选取\n")
f.write("```\n\n")
f.write("ggml_mul_mat_id 在 Vulkan 后端的执行流程：\n")
f.write("1. GGML 图调度器遍历所有 op 节点\n")
f.write("2. 遇到 GGML_OP_MUL_MAT_ID:\n")
f.write("   - Vulkan 后端查找对应的 shader（mul_mat_id.comp）\n")
f.write("   - 将 selected_experts 索引 tensor 上传到 GPU\n")
f.write("   - 对每个选中的 expert id，执行 shader dispatch\n")
f.write("3. Dispatch 时，从 3D tensor 中按 expert id 切片\n")
f.write("4. 执行标准矩阵乘法，结果写回输出 tensor\n\n")
f.write("**学习重点**：要实现专家卸载，需要在 GGML 层新增\n")
f.write("GGML_OP_MUL_MAT_ID_OFFLOAD 或在 Vulkan shader 中\n")
f.write("新增 lazy loading 逻辑，让 shader 直接处理按需加载。\n\n")
f.write("---\n\n")
f.write("## 第四部分：学习路线图\n\n")
f.write("### Phase 1：理解现有代码（2-3 周）\n\n")
f.write("| 优先级 | 学习内容 | 关键文件 |\n")
f.write("|---|---|---|\n")
f.write("| ★★★ | MoE 核心路由计算 | llama-graph.cpp:1326-1722 |\n")
f.write("| ★★★ | Qwen3.5MoE 模型定义 | src/models/qwen35moe.cpp |\n")
f.write("| ★★★ | 模型加载与 tensor 注册 | llama-model-loader.cpp |\n")
f.write("| ★★☆ | 推理主循环 | llama-impl.cpp |\n")
f.write("| ★★☆ | 超参数定义 | llama-hparams.h |\n")
f.write("| ★★☆ | Vulkan 后端 shader 管线 | ggml-vulkan/ |\n")
f.write("| ★☆☆ | GGML 核心 op 定义 | ggml.c, ggml-impl.h |\n")
f.write("| ★☆☆ | 张量形状与数据布局 | ggml-common.h |\n\n")
f.write("### Phase 2：理解论文技术（1-2 周）\n\n")
f.write("| 论文 | 核心贡献 | 学习重点 |\n")
f.write("|---|---|---|\n")
f.write("| ExpertFlow | 路由预测+预取+token 调度 | Predict->Schedule->Prefetch 流水线 |\n")
f.write("| Speculating Experts | Quasi-hidden state 预取 | 残差流预测下一层路由 |\n")
f.write("| FlashMoE | ML-based cache replacement | 超越 LRU/LFU 的混合策略 |\n")
f.write("| Fast MoE Inference | SRU 预测+专家复制 | Batch 级预测与负载均衡 |\n\n")
f.write("### Phase 3：实现方案（长期）\n\n")
f.write("按实现顺序：\n")
f.write("1. **专家 tensor 独立分配** — 修改 llama-model-loader.cpp\n")
f.write("   当前：专家权重是 3D tensor [n_ff, n_embd, n_expert]\n")
f.write("   改为：每个专家分配独立 2D tensor，或 mmap 按需加载\n\n")
f.write("2. **专家缓存管理** — 新增 src/llama-expert-cache.cpp\n")
f.write("   DRAM expert cache（固定大小，如 32GB）\n")
f.write("   LRU + 频率信号的混合 eviction 策略\n")
f.write("   SSD -> DRAM 异步预取流水线\n\n")
f.write("3. **路由预测器** — 在 llama-graph.cpp 中新增\n")
f.write("   预填充阶段：执行所有 gate_inp 收集完整路由矩阵\n")
f.write("   解码阶段：quasi-hidden state 预测下一层\n")
f.write("   Token scheduling：K-means 聚类合并相似路由\n\n")
f.write("4. **GGML op 扩展** — 在 ggml.c + Vulkan 后端\n")
f.write("   新增 GGML_OP_MUL_MAT_ID_OFFLOAD 支持 lazy loading\n")
f.write("   修改计算图调度器支持异步加载\n\n")
f.write("---\n\n")
f.write("## 附录：关键术语表\n\n")
f.write("| 术语 | 含义 |\n")
f.write("|---|---|\n")
f.write("| MoE | Mixture-of-Experts，混合专家模型 |\n")
f.write("| Expert | 专家子网络，MoE 层的独立 FFN |\n")
f.write("| Router | 路由门控，决定 token 激活哪些专家 |\n")
f.write("| Top-K | 选择概率最高的 K 个专家 |\n")
f.write("| Shared Expert | 对所有 token 始终激活的公共专家 |\n")
f.write("| mul_mat_id | 带索引选择的矩阵乘法（MoE 核心 Op） |\n")
f.write("| Hybrid | 混合 attention+recurrent 层（Qwen3.5） |\n")
f.write("| Unified Memory | CPU+GPU 共享 DRAM（AMD 395） |\n")
f.write("| Quasi-Hidden State | 残差流预测下一层路由 |\n")
f.write("| Expert Offloading | 将非活跃专家卸载到低层存储 |\n")
f.write("| KVCache | Key-Value 缓存，解码避免重复计算 |\n")
f.write("| MTP | Multi-Token Prediction（Qwen3.5 多 token 预测头）|\n\n")
f.close()
print("Part E done")
